# Generated by Django 4.0.1 on 2022-01-12 16:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('do_projects', '0002_doproject_company_alter_doproject_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manager', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('channel_of_usage', models.CharField(blank=True, choices=[('c', 'correspondence'), ('p', 'phone'), ('p', 'calls'), ('m', 'mail'), ('e', 'email')], default='m', max_length=1)),
                ('rating', models.CharField(blank=True, choices=[('+5', 'masterpiece'), ('+4', 'great'), ('+3', 'very good'), ('+2', 'good'), ('+1', 'not bad'), ('0', 'mediocre'), ('-1', 'no way'), ('-2', 'bad'), ('-3', 'terrible'), ('-4', 'negligible')], default='0', max_length=2)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='do_projects.doproject')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
