# Generated by Django 4.0.1 on 2022-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='channel_of_usage',
            field=models.CharField(blank=True, choices=[('c', 'correspondence'), ('p', 'phone'), ('i', 'company initiative'), ('m', 'mail'), ('e', 'email')], default='m', max_length=1),
        ),
    ]
