company_name = [
    'Discreet test',
    'test Tips',
    'Feature Test',
    'Fiber test',
    'People test',
    'test Land',
    'Order test',
    'Rally test',
    'Test Dynamics',
    'Terrific test',
    'JustRight test',
    'Kronos test',
    'Shop test',
    'Feather test',
    'Fission test',
    'Atlantis test',
    'test Razor',
    'test House',
    'Revision test',
    'Profound test',
    'Vinci test',
    'test Gamer',
    'Press test',
    'Exclusive test',
    'Europa test',
]